### ISSUE TITLE
What is the difference between with and without using --load_weights when using Prediction.py?

### ISSUE THREAD

**Issue by irleader** [ProteomeTeam/NovoB#1]
There are two examples using Prediction.py"

python Prediction.py -m NovoBInit/ --load_weights TrainedModel/usingCasanovoDataSet/yeast/variables/variables
python Prediction.py -m TrainedModel/usingCasanovoDataSet/yeast/

one with NovoBInit and --load weigths as well as the variables.
The other with the whole folder of trained model.

Will the output be different or the same? if different, what is the difference. Thanks a lot.

**Comment by pardess** [comment]
NovoB is loaded model or model+weight.
If you want to load the learned model, don't use the --load_weights option.
Depending on your tensorflow version, if --save_model is not available, you must use --save_weights to save the weights.
In this case, you can load the saved weights using --load_weights.
