### ISSUE TITLE
train with multiple files and save model at best validation performance

### ISSUE THREAD

**Issue by irleader** [ProteomeTeam/NovoB#2]
Hi,

I tried to train the model, and it seems it can only be trained with one file, and it saves the model at the end of training, e.g. after 30 epoches.

Is it possible to train NovoB with multiple .mgf files? Also, how can we save the trained model when at best validation performance? Thanks a lot!

**Comment by pardess** [comment]
Currently, only single mgf file is possible and model saving is only possible after 30 epoches. We will try to update it later.
If you want to use multiple files, you can combine them into single file.

**Comment by irleader** [comment]
Thanks a lot for your prompt answer. I will be looking forward to using NovoB to train on our own data.
