### ISSUE TITLE
Pretrianed model on a large dataset

### ISSUE THREAD

**Issue by irleader** [ProteomeTeam/NovoB#4]
Hi,

Is it possible to share with us a model checkpoint which has been trained on a huge dataset like massivekb used by casanovo? I am afraid that the models trained on graphnovo dataset and nine-species dataset can not fully exhibit the power of NovoB.

Thanks a lot!

**Comment by pardess** [comment]
We do not yet have a model checkpoint trained on huge datasets like massivekb. As you said, the checkpoints we provide are not enough.

Currently, I am thinking about which dataset would be best to use for training. Additionally, efforts are being made to improve accuracy.

**Comment by irleader** [comment]
Thanks a lot for your feedback!
